version: "3"

services:
  otel-datadog:
    image: datadog/agent:latest
    pid: host
    ports:
      - "4318:4318"
      - "5003:5003"
      - "8125:8125"
      - "6162:6162"
      - "8126:8126"
      - "4319:4317"
      - "4320:4318"
    environment:
      - DD_API_KEY=e888a50f69f41d9f186b393292ff09f4
      - DD_SITE=us5.datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
      - DD_OTLP_CONFIG_TRACES_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
